# Generated by Django 5.2.13 on 2026-05-11 17:13

import app.models.basketball.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_team_logo_imagefield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="season_year",
            field=models.IntegerField(
                default=app.models.basketball.models.get_current_year
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="season_year",
            field=models.IntegerField(
                default=app.models.basketball.models.get_current_year
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="division",
            field=models.CharField(
                choices=[
                    ("midget", "Midget"),
                    ("senior", "Senior"),
                    ("junior", "Junior"),
                    ("U13", "U13"),
                    ("U14", "U14"),
                    ("U15", "U15"),
                    ("U16", "U16"),
                    ("U17", "U17"),
                    ("U18", "U18"),
                    ("U19", "U19"),
                    ("U20", "U20"),
                    ("U21", "U21"),
                ],
                max_length=20,
            ),
        ),
    ]
