LOCATIONS = {
    "regions": [
        {"id": 1, "name": "Cagwait"},
        {"id": 2, "name": "Bayabas"},
        {"id": 3, "name": "Marihatag"},
    ],
    "provinces": {
        1: [
            {"id": 11, "name": "Aras-asan"},
            {"id": 12, "name": "Bacolod"},
            {"id": 13, "name": "Bitaugan East"},
            {"id": 14, "name": "Bitaugan West"},
            {"id": 15, "name": "La Purisima"},
            {"id": 16, "name": "Lactudan"},
            {"id": 17, "name": "Mat-e"},
            {"id": 18, "name": "Poblacion"},
            {"id": 19, "name": "Tawagan"},
            {"id": 20, "name": "Tubo-tubo"},
            {"id": 21, "name": "Unidad"},
        ],
        2: [
            {"id": 22, "name": "Amag"},
            {"id": 23, "name": "Balete (Poblacion)"},
            {"id": 24, "name": "Cabugo"},
            {"id": 25, "name": "Cagbaoto"},
            {"id": 26, "name": "La Paz"},
            {"id": 27, "name": "Magobawok"},
            {"id": 28, "name": "Panaosawon"},
        ],
        3: [
            {"id": 29, "name": "Alegria"},
            {"id": 30, "name": "Amontay"},
            {"id": 31, "name": "Antipolo"},
            {"id": 32, "name": "Arorogan"},
            {"id": 33, "name": "Bayan"},
            {"id": 34, "name": "Mahaba"},
            {"id": 35, "name": "Mararag"},
            {"id": 36, "name": "Poblacion"},
            {"id": 37, "name": "San Antonio"},
            {"id": 38, "name": "San Isidro"},
            {"id": 39, "name": "San Pedro"},
            {"id": 40, "name": "Sta Cruz"},
        ],
    },
    "cities": {
        11: [{"id": 111, "name": "Aras-asan"}],
        12: [{"id": 112, "name": "Bacolod"}],
        13: [{"id": 113, "name": "Bitaugan East"}],
        14: [{"id": 114, "name": "Bitaugan West"}],
        15: [{"id": 115, "name": "La Purisima"}],
        16: [{"id": 116, "name": "Lactudan"}],
        17: [{"id": 117, "name": "Mat-e"}],
        18: [{"id": 118, "name": "Poblacion"}],
        19: [{"id": 119, "name": "Tawagan"}],
        20: [{"id": 120, "name": "Tubo-tubo"}],
        21: [{"id": 121, "name": "Unidad"}],
        22: [{"id": 122, "name": "Amag"}],
        23: [{"id": 123, "name": "Balete (Poblacion)"}],
        24: [{"id": 124, "name": "Cabugo"}],
        25: [{"id": 125, "name": "Cagbaoto"}],
        26: [{"id": 126, "name": "La Paz"}],
        27: [{"id": 127, "name": "Magobawok"}],
        28: [{"id": 128, "name": "Panaosawon"}],
        29: [{"id": 129, "name": "Alegria"}],
        30: [{"id": 130, "name": "Amontay"}],
        31: [{"id": 131, "name": "Antipolo"}],
        32: [{"id": 132, "name": "Arorogan"}],
        33: [{"id": 133, "name": "Bayan"}],
        34: [{"id": 134, "name": "Mahaba"}],
        35: [{"id": 135, "name": "Mararag"}],
        36: [{"id": 136, "name": "Poblacion"}],
        37: [{"id": 137, "name": "San Antonio"}],
        38: [{"id": 138, "name": "San Isidro"}],
        39: [{"id": 139, "name": "San Pedro"}],
        40: [{"id": 140, "name": "Sta Cruz"}],
    },
}


def list_regions():
    return LOCATIONS["regions"]
